// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "GPL-3.0",
            "url": "https://www.gnu.org/licenses/gpl-3.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/animes": {
            "get": {
                "description": "Returns a list of animes with aggregated episode information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "animes"
                ],
                "summary": "Get animes list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.AnimeInfo"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/animes/{id}/episodes": {
            "get": {
                "description": "Returns anime info from AniList combined with downloaded episodes data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "animes"
                ],
                "summary": "Get detail and episodes for a specific anime",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID (AniList MediaList ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.AnimeDetailResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/animes/{id}/episodes/{episodeId}": {
            "delete": {
                "description": "Deletes a downloaded episode from qBittorrent and blocks it from being re-downloaded automatically",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "animes"
                ],
                "summary": "Manually delete a downloaded episode",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID (AniList MediaList ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Episode ID (AniList AiringNode ID)",
                        "name": "episodeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/animes/{id}/episodes/{episodeId}/download": {
            "post": {
                "description": "Triggers an immediate download for an aired episode and marks it as manually managed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "animes"
                ],
                "summary": "Manually download an episode",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID (AniList MediaList ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Episode ID (AniList AiringNode ID)",
                        "name": "episodeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/animes/{id}/episodes/{episodeId}/redownload": {
            "post": {
                "description": "Deletes the existing torrent (if any) and searches Nyaa again for a fresh download",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "animes"
                ],
                "summary": "Redownload an episode from Nyaa",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID (AniList MediaList ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Episode ID (AniList AiringNode ID)",
                        "name": "episodeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/animes/{id}/episodes/{episodeId}/release": {
            "post": {
                "description": "Unblocks and unmanages an episode so the daemon can handle it automatically again",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "animes"
                ],
                "summary": "Release an episode from manual management",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID (AniList MediaList ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Episode ID (AniList AiringNode ID)",
                        "name": "episodeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/animes/{id}/episodes/{episodeId}/replace": {
            "post": {
                "description": "Deletes the existing torrent (if any) and downloads the episode using the provided magnet link",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "animes"
                ],
                "summary": "Replace a downloaded episode with a user-supplied magnet link",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID (AniList MediaList ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Episode ID (AniList AiringNode ID)",
                        "name": "episodeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Magnet link",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/animes/{id}/replace": {
            "post": {
                "description": "Deletes all existing torrents for the anime and downloads using the provided magnet link, marking all aired episodes as downloaded",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "animes"
                ],
                "summary": "Replace all downloaded episodes of an anime with a user-supplied batch magnet link",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID (AniList MediaList ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Magnet link",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/animes/{id}/settings": {
            "get": {
                "description": "GET returns current settings; PUT updates them",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "animes"
                ],
                "summary": "Get or update anime-specific settings",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID (AniList MediaList ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Settings",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.animeSettingsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "GET returns current settings; PUT updates them",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "animes"
                ],
                "summary": "Get or update anime-specific settings",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID (AniList MediaList ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Settings",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.animeSettingsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/check": {
            "post": {
                "description": "Triggers a manual anime verification check",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "daemon"
                ],
                "summary": "Trigger manual check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/config": {
            "get": {
                "description": "Returns the current daemon configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/files.Config"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates the daemon configuration with the provided values",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Update configuration",
                "parameters": [
                    {
                        "description": "Configuration object",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/files.Config"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/config/priorities/defaults": {
            "get": {
                "description": "Returns the built-in default priority lists (for the \"reset to default\" button)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get default torrent priorities",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/nyaa.Priorities"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/daemon/start": {
            "post": {
                "description": "Starts the daemon loop for automatic anime checking",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "daemon"
                ],
                "summary": "Start daemon",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/daemon/stop": {
            "post": {
                "description": "Stops the daemon loop",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "daemon"
                ],
                "summary": "Stop daemon",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/logs": {
            "get": {
                "description": "Returns the last N lines from the daemon log file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Get daemon logs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of lines to return (default: 1000, max: 10000)",
                        "name": "lines",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.LogsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/notifications/webhooks/{name}/test": {
            "post": {
                "description": "Fires a named webhook with sample variables to verify connectivity",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Test a webhook preset",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Webhook preset name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "Returns the current status of the daemon, including last check time, error state, and disk space for the configured save path",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "status"
                ],
                "summary": "Get daemon status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.StatusResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.AnimeDetailResponse": {
            "type": "object",
            "properties": {
                "anilist_id": {
                    "type": "integer",
                    "example": 21
                },
                "anime_id": {
                    "type": "integer"
                },
                "cover_image": {
                    "type": "string"
                },
                "custom_search_query": {
                    "type": "string"
                },
                "episodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.AnimeEpisodeInfo"
                    }
                },
                "progress": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "total_episodes": {
                    "type": "integer"
                }
            }
        },
        "api.AnimeEpisodeInfo": {
            "type": "object",
            "properties": {
                "airing_at": {
                    "type": "integer"
                },
                "download_date": {
                    "type": "string"
                },
                "episode_id": {
                    "type": "integer"
                },
                "episode_name": {
                    "type": "string"
                },
                "episode_number": {
                    "type": "integer"
                },
                "is_aired": {
                    "type": "boolean"
                },
                "is_blocked": {
                    "type": "boolean"
                },
                "is_downloaded": {
                    "type": "boolean"
                },
                "is_manually_managed": {
                    "type": "boolean"
                },
                "is_watched": {
                    "type": "boolean"
                },
                "time_until_airing": {
                    "type": "integer"
                }
            }
        },
        "api.AnimeInfo": {
            "type": "object",
            "properties": {
                "anime_id": {
                    "type": "integer",
                    "example": 12345
                },
                "cover_image": {
                    "type": "string"
                },
                "episodes_downloaded": {
                    "type": "integer",
                    "example": 8
                },
                "episodes_released": {
                    "type": "integer",
                    "example": 10
                },
                "episodes_watched": {
                    "type": "integer",
                    "example": 5
                },
                "is_blacklisted": {
                    "type": "boolean"
                },
                "last_download_date": {
                    "type": "string",
                    "example": "2026-02-24T10:30:00Z"
                },
                "latest_episode_id": {
                    "type": "integer",
                    "example": 12
                },
                "name": {
                    "type": "string",
                    "example": "Naruto"
                },
                "total_episodes": {
                    "type": "integer",
                    "example": 12
                }
            }
        },
        "api.ErrorInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "api.LogsResponse": {
            "type": "object",
            "properties": {
                "lines": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.StatusResponse": {
            "type": "object",
            "properties": {
                "disk_free": {
                    "type": "integer",
                    "example": 128849018880
                },
                "disk_total": {
                    "type": "integer",
                    "example": 500107862016
                },
                "has_error": {
                    "type": "boolean",
                    "example": false
                },
                "last_check": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "status": {
                    "type": "string",
                    "example": "running"
                },
                "version": {
                    "type": "string",
                    "example": "1.2.0"
                }
            }
        },
        "api.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/api.ErrorInfo"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "api.animeSettingsRequest": {
            "type": "object",
            "properties": {
                "custom_search_query": {
                    "type": "string"
                }
            }
        },
        "files.Config": {
            "type": "object",
            "properties": {
                "anilist_username": {
                    "type": "string"
                },
                "anilist_usernames": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "check_interval": {
                    "type": "integer"
                },
                "completed_anime_path": {
                    "type": "string"
                },
                "delete_statuses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "delete_watched_episodes": {
                    "type": "boolean"
                },
                "download_media_statuses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "download_statuses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "episode_retry_limit": {
                    "type": "integer"
                },
                "excluded_list": {
                    "type": "string"
                },
                "excluded_lists": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "max_episodes_per_anime": {
                    "type": "integer"
                },
                "notifications": {
                    "$ref": "#/definitions/files.NotificationsConfig"
                },
                "priorities": {
                    "$ref": "#/definitions/nyaa.Priorities"
                },
                "qbittorrent_url": {
                    "type": "string"
                },
                "rename_files_for_jellyfin": {
                    "type": "boolean"
                },
                "save_path": {
                    "type": "string"
                },
                "watched_episodes_to_keep": {
                    "type": "integer"
                }
            }
        },
        "files.NotificationsConfig": {
            "type": "object",
            "properties": {
                "webhooks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/files.WebhookPreset"
                    }
                }
            }
        },
        "files.WebhookPreset": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "events": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "method": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "nyaa.Priorities": {
            "type": "object",
            "properties": {
                "audio": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "codecs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "criteria_order": {
                    "description": "CriteriaOrder é a ordem em que os critérios de sort são aplicados.\nValores válidos: uncensored, source, resolution, codec, fansub, audio, health, size.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "fansubs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ignore_list": {
                    "description": "IgnoreList: substrings (case-insensitive) que descartam o release de vez.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "resolutions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sources": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8091",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Auto Anime Downloader API",
	Description:      "REST API for Auto Anime Downloader daemon",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
