// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "GPL-3.0",
            "url": "https://www.gnu.org/licenses/gpl-3.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/animes": {
            "get": {
                "description": "Returns a list of animes with aggregated episode information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "animes"
                ],
                "summary": "Get animes list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.AnimeInfo"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/animes/{id}/episodes": {
            "get": {
                "description": "Returns anime info from AniList combined with downloaded episodes data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "animes"
                ],
                "summary": "Get detail and episodes for a specific anime",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID (AniList media ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.AnimeDetailResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/animes/{id}/episodes/{episodeId}": {
            "delete": {
                "description": "Deletes a downloaded episode (library hardlink + torrent) and blocks it from being re-downloaded automatically",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "animes"
                ],
                "summary": "Manually delete a downloaded episode",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID (AniList MediaList ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Episode ID (AniList AiringNode ID)",
                        "name": "episodeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/animes/{id}/episodes/{episodeId}/download": {
            "post": {
                "description": "Triggers an immediate download for an aired episode and marks it as manually managed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "animes"
                ],
                "summary": "Manually download an episode",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID (AniList MediaList ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Episode ID (AniList AiringNode ID)",
                        "name": "episodeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/animes/{id}/episodes/{episodeId}/redownload": {
            "post": {
                "description": "Deletes the existing torrent (if any) and searches Nyaa again for a fresh download",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "animes"
                ],
                "summary": "Redownload an episode from Nyaa",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID (AniList MediaList ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Episode ID (AniList AiringNode ID)",
                        "name": "episodeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/animes/{id}/episodes/{episodeId}/release": {
            "post": {
                "description": "Unblocks and unmanages an episode so the daemon can handle it automatically again",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "animes"
                ],
                "summary": "Release an episode from manual management",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID (AniList MediaList ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Episode ID (AniList AiringNode ID)",
                        "name": "episodeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/animes/{id}/episodes/{episodeId}/replace": {
            "post": {
                "description": "Deletes the existing torrent (if any) and downloads the episode using the provided magnet link",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "animes"
                ],
                "summary": "Replace a downloaded episode with a user-supplied magnet link",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID (AniList MediaList ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Episode ID (AniList AiringNode ID)",
                        "name": "episodeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Magnet link",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/animes/{id}/replace": {
            "post": {
                "description": "Deletes all existing torrents for the anime and downloads using the provided magnet link, marking all aired episodes as downloaded",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "animes"
                ],
                "summary": "Replace all downloaded episodes of an anime with a user-supplied batch magnet link",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID (AniList MediaList ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Magnet link",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/animes/{id}/settings": {
            "get": {
                "description": "GET returns current settings; PUT updates them",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "animes"
                ],
                "summary": "Get or update anime-specific settings",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID (AniList MediaList ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Settings",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.animeSettingsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "GET returns current settings; PUT updates them",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "animes"
                ],
                "summary": "Get or update anime-specific settings",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID (AniList MediaList ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Settings",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.animeSettingsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/check": {
            "post": {
                "description": "Triggers a manual anime verification check",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "daemon"
                ],
                "summary": "Trigger manual check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/config": {
            "get": {
                "description": "Returns the current daemon configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/files.Config"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates the daemon configuration with the provided values",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Update configuration",
                "parameters": [
                    {
                        "description": "Configuration object",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/files.Config"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/config/priorities/defaults": {
            "get": {
                "description": "Returns the built-in default priority lists (for the \"reset to default\" button)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get default torrent priorities",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/nyaa.Priorities"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/daemon/start": {
            "post": {
                "description": "Starts the daemon loop for automatic anime checking",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "daemon"
                ],
                "summary": "Start daemon",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/daemon/stop": {
            "post": {
                "description": "Stops the daemon loop",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "daemon"
                ],
                "summary": "Stop daemon",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/logs": {
            "get": {
                "description": "Returns the last N lines from the daemon log file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Get daemon logs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of lines to return (default: 1000, max: 10000)",
                        "name": "lines",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.LogsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/notifications/webhooks/{name}/test": {
            "post": {
                "description": "Fires a named webhook with sample variables to verify connectivity",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Test a webhook preset",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Webhook preset name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "Returns the current status of the daemon, including last check time, error state, and disk space for the configured save path",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "status"
                ],
                "summary": "Get daemon status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.StatusResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/torrents": {
            "get": {
                "description": "Returns a live snapshot of every torrent in the embedded client — progress, speed, ETA, peers and status — joined with the anime/episode it belongs to. Batch torrents appear once, with a null episode_number. Responds with an empty list (not an error) when no session exists yet, i.e. before completed_anime_path is configured.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "torrents"
                ],
                "summary": "List torrents",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.TorrentResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/torrents/prioritize": {
            "post": {
                "description": "Moves every listed torrent to the FRONT of the download queue, in the order received, and starts as many as max_concurrent_downloads allows — whatever is pushed past the limit pauses. Unknown or already-completed hashes are ignored rather than rejected: a list of episodes must not fail whole because one of them finished between the render and the click. Use this instead of N calls to /torrents/{hash}/prioritize, which would reverse the batch.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "torrents"
                ],
                "summary": "Prioritize several torrents at once",
                "parameters": [
                    {
                        "description": "Info hashes, most important first",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.PrioritizeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/torrents/{hash}": {
            "delete": {
                "description": "Removes a torrent and every saved episode sharing its hash, as a single unit (the deletion boundary is the torrent, not the episode, so a batch's episodes always leave together). By default this frees both the seeding copy and the library hardlink (same inode); keep_data=true keeps both instead. block=true additionally blocks every episode in the group against automatic re-download.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "torrents"
                ],
                "summary": "Delete a torrent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Torrent info hash",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Keep the seeding copy and library hardlinks on disk (default false)",
                        "name": "keep_data",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Block the torrent's episodes against automatic re-download (default false)",
                        "name": "block",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/torrents/{hash}/announce": {
            "post": {
                "description": "Re-announces the torrent to all trackers and DHT — the way out of \"stuck at 0 peers\". It does not override the trackers' minimum interval, so repeated calls have no extra effect.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "torrents"
                ],
                "summary": "Force a torrent re-announce",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Torrent info hash",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/torrents/{hash}/pause": {
            "post": {
                "description": "Stops a torrent. Does not block: the torrent enters the \"stopping\" state and only reaches \"stopped\" up to ~5s later, once the stop event reaches the trackers. The paused state is persisted and survives a daemon restart.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "torrents"
                ],
                "summary": "Pause a torrent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Torrent info hash",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/torrents/{hash}/prioritize": {
            "post": {
                "description": "Moves a torrent to the FRONT of the download queue and starts it immediately, pausing the least-progressed active torrent when that would exceed max_concurrent_downloads. Nothing is lost by the demotion — rain keeps the piece bitfield across a stop. A torrent that is already downloading is a no-op; an already-completed one is a 500.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "torrents"
                ],
                "summary": "Prioritize a torrent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Torrent info hash",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/torrents/{hash}/resume": {
            "post": {
                "description": "Puts a paused torrent at the BACK of the download queue and starts it if a slot is free — with max_concurrent_downloads set, resuming does not mean \"start now\" (use /prioritize for that). Re-arms the completion listener. A completed (seeding) torrent bypasses the queue.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "torrents"
                ],
                "summary": "Resume a torrent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Torrent info hash",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.AnimeDetailResponse": {
            "type": "object",
            "properties": {
                "anime_id": {
                    "description": "AnimeID e o id da MIDIA na AniList — a mesma chave usada em episodes.json e nas rotas\n/animes/{id}/*, e tambem o id do link anilist.co/anime/{id} (ver decisions.md #43).",
                    "type": "integer"
                },
                "cover_image": {
                    "type": "string"
                },
                "custom_search_query": {
                    "type": "string"
                },
                "episodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.AnimeEpisodeInfo"
                    }
                },
                "progress": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "total_episodes": {
                    "type": "integer"
                }
            }
        },
        "api.AnimeEpisodeInfo": {
            "type": "object",
            "properties": {
                "airing_at": {
                    "type": "integer"
                },
                "download_date": {
                    "type": "string"
                },
                "episode_hash": {
                    "description": "EpisodeHash is the saved episode's torrent info hash. It is what lets the anime detail\nscreen join in live torrent progress exactly: a batch torrent's saved episodes all carry\nthe same hash but episode_number is meaningless for matching a torrent to them (the\ntorrent itself has no single episode number), so joining by number would miss batches\nentirely. Joining by hash instead, single and batch episodes use the same path. Empty\n(and omitted via omitempty) when the episode has no saved record.",
                    "type": "string"
                },
                "episode_id": {
                    "type": "integer"
                },
                "episode_name": {
                    "type": "string"
                },
                "episode_number": {
                    "type": "integer"
                },
                "is_aired": {
                    "type": "boolean"
                },
                "is_blocked": {
                    "type": "boolean"
                },
                "is_downloaded": {
                    "type": "boolean"
                },
                "is_manually_managed": {
                    "type": "boolean"
                },
                "is_watched": {
                    "type": "boolean"
                },
                "time_until_airing": {
                    "type": "integer"
                }
            }
        },
        "api.AnimeInfo": {
            "type": "object",
            "properties": {
                "anime_id": {
                    "type": "integer",
                    "example": 12345
                },
                "cover_image": {
                    "type": "string"
                },
                "episodes_downloaded": {
                    "type": "integer",
                    "example": 8
                },
                "episodes_pending": {
                    "description": "EpisodesPending conta episodios ja lancados, ainda nao assistidos e ainda nao baixados.\nEpisodio assistido nunca e baixado (daemon.shouldSkipEpisode), entao ele nao pode contar\ncomo atraso — era isso que marcava meia lista como \"atrasado\" no frontend.",
                    "type": "integer",
                    "example": 2
                },
                "episodes_released": {
                    "type": "integer",
                    "example": 10
                },
                "episodes_watched": {
                    "type": "integer",
                    "example": 5
                },
                "is_blacklisted": {
                    "type": "boolean"
                },
                "last_download_date": {
                    "type": "string",
                    "example": "2026-02-24T10:30:00Z"
                },
                "latest_episode_id": {
                    "type": "integer",
                    "example": 12
                },
                "name": {
                    "type": "string",
                    "example": "Naruto"
                },
                "total_episodes": {
                    "type": "integer",
                    "example": 12
                }
            }
        },
        "api.ErrorInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "api.LogsResponse": {
            "type": "object",
            "properties": {
                "lines": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.PrioritizeRequest": {
            "type": "object",
            "properties": {
                "hashes": {
                    "description": "Hashes is applied IN THE ORDER RECEIVED — the frontend decides the order, because it is\nwhat knows what the user clicked.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "0123456789abcdef0123456789abcdef01234567"
                    ]
                }
            }
        },
        "api.StatusResponse": {
            "type": "object",
            "properties": {
                "disk_free": {
                    "type": "integer",
                    "example": 128849018880
                },
                "disk_low": {
                    "description": "DiskLow marca que o livre esta abaixo de min_free_disk_percent — ou seja, que o daemon\nPAROU de adicionar torrents. Calculado no servidor de proposito: um limiar duplicado no\nfrontend acabaria discordando do que o daemon esta fazendo.",
                    "type": "boolean",
                    "example": false
                },
                "disk_total": {
                    "type": "integer",
                    "example": 500107862016
                },
                "has_error": {
                    "type": "boolean",
                    "example": false
                },
                "last_check": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "status": {
                    "type": "string",
                    "example": "running"
                },
                "version": {
                    "type": "string",
                    "example": "1.2.0"
                }
            }
        },
        "api.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/api.ErrorInfo"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "api.TorrentResponse": {
            "type": "object",
            "properties": {
                "anime_id": {
                    "type": "integer",
                    "example": 154587
                },
                "anime_name": {
                    "type": "string",
                    "example": "Sousou no Frieren"
                },
                "bytes_completed": {
                    "type": "integer",
                    "example": 524288000
                },
                "bytes_total": {
                    "description": "BytesTotal is 0 until the torrent's metadata arrives.",
                    "type": "integer",
                    "example": 1073741824
                },
                "bytes_uploaded": {
                    "type": "integer",
                    "example": 104857600
                },
                "completed": {
                    "description": "Completed is piece-derived (TorrentInfo.Completed), not Status-derived — it stays true\nfor a torrent paused after finishing, which Status alone cannot tell apart from a\npaused, unfinished one. Used to key the list sort instead of Status.",
                    "type": "boolean",
                    "example": false
                },
                "download_speed": {
                    "type": "integer",
                    "example": 2097152
                },
                "episode_number": {
                    "description": "EpisodeNumber is null for batch torrents (they map to several episodes).",
                    "type": "integer"
                },
                "eta_seconds": {
                    "description": "EtaSeconds is null when unknown or infinite.",
                    "type": "integer",
                    "example": 240
                },
                "hash": {
                    "type": "string",
                    "example": "0123456789abcdef0123456789abcdef01234567"
                },
                "is_batch": {
                    "type": "boolean",
                    "example": false
                },
                "name": {
                    "type": "string",
                    "example": "[SubsPlease] Frieren - 07 (1080p).mkv"
                },
                "peers_total": {
                    "type": "integer",
                    "example": 14
                },
                "progress": {
                    "description": "Progress is 0..1: BytesCompleted/BytesTotal normally, falling back to the piece ratio\n(PiecesHave/PiecesTotal) when BytesCompleted reads 0 with a paused torrent — see\nbuildTorrentResponse. 0 while BytesTotal and PiecesTotal are both unknown.",
                    "type": "number",
                    "example": 0.48
                },
                "queue_position": {
                    "description": "QueuePosition is the 1-based place in the download queue's waiting line; 0 means the\ntorrent is not waiting (active, completed, or paused by the user). Not a pointer: 0\nalready says \"not queued\" without ambiguity — there is no position 0.",
                    "type": "integer",
                    "example": 3
                },
                "seeded_for_seconds": {
                    "type": "integer",
                    "example": 3600
                },
                "status": {
                    "type": "string",
                    "example": "downloading"
                },
                "upload_speed": {
                    "type": "integer",
                    "example": 524288
                }
            }
        },
        "api.animeSettingsRequest": {
            "type": "object",
            "properties": {
                "custom_search_query": {
                    "type": "string"
                }
            }
        },
        "files.Config": {
            "type": "object",
            "properties": {
                "anilist_username": {
                    "type": "string"
                },
                "anilist_usernames": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "anime_ids_are_media_ids": {
                    "description": "AnimeIDsAreMediaIDs marca que daemon.MigrateAnimeIDsToMedia ja converteu os AnimeID\ngravados de id de ENTRADA (MediaList, por conta) para id de MIDIA (ver decisions.md #43).\nO default e false de proposito: um config.json anterior a este campo desserializa por\ncima do default e precisa migrar. Numa instalacao nova a migracao roda sem nada a fazer\ne liga o campo no primeiro passe.",
                    "type": "boolean"
                },
                "check_interval": {
                    "type": "integer"
                },
                "completed_anime_path": {
                    "type": "string"
                },
                "delete_statuses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "delete_watched_episodes": {
                    "type": "boolean"
                },
                "download_media_statuses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "download_statuses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "episode_retry_limit": {
                    "type": "integer"
                },
                "excluded_list": {
                    "type": "string"
                },
                "excluded_lists": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "max_batch_episodes": {
                    "description": "MaxBatchEpisodes e o teto de episodios para usar batch. Acima disso um anime finalizado\nvolta ao caminho episodio-a-episodio (onde MaxEpisodesPerAnime vale). 0 desliga o teto.",
                    "type": "integer"
                },
                "max_batch_torrent_size_gb": {
                    "description": "MaxBatchTorrentSizeGB / MaxEpisodeTorrentSizeGB descartam da busca torrents acima do teto,\nem GiB. 0 desliga (default: nao filtrar, pois nao existe numero defensavel sem saber se o\nusuario quer 1080p web ou remux).",
                    "type": "number"
                },
                "max_concurrent_downloads": {
                    "description": "MaxConcurrentDownloads limita quantos torrents INCOMPLETOS baixam ao mesmo tempo; o\nexcedente espera na fila (torrents.queue). 0 desliga o limite. Seeding nunca conta.\n\nNao precisa de migracao: LoadConfigs desserializa POR CIMA de getDefaultConfig(),\nentao um config.json anterior a este campo ja carrega valendo o default.",
                    "type": "integer"
                },
                "max_episode_torrent_size_gb": {
                    "type": "number"
                },
                "max_episodes_per_anime": {
                    "description": "MaxEpisodesPerAnime limita quantos episodios de um anime existem ao mesmo tempo, e vale\nAPENAS no caminho episodio-a-episodio: um batch e um torrent so, entao limitar registros\nnao limitaria bytes nem arquivos na biblioteca (ver decisions.md).",
                    "type": "integer"
                },
                "min_free_disk_percent": {
                    "description": "MinFreeDiskPercent barra a adicao de novos torrents abaixo dessa porcentagem de espaco\nlivre no volume da biblioteca. 0 desliga.",
                    "type": "integer"
                },
                "notifications": {
                    "$ref": "#/definitions/files.NotificationsConfig"
                },
                "priorities": {
                    "$ref": "#/definitions/nyaa.Priorities"
                },
                "rename_files_for_jellyfin": {
                    "type": "boolean"
                },
                "watched_episodes_to_keep": {
                    "type": "integer"
                }
            }
        },
        "files.NotificationsConfig": {
            "type": "object",
            "properties": {
                "batch_window_seconds": {
                    "description": "BatchWindowSeconds agrupa os eventos de uma mesma janela num webhook so. 0 desliga o\nagrupamento (um webhook por evento, comportamento original). Existe porque um backfill\nde biblioteca dispara um ` + "`" + `download_completed` + "`" + ` por torrent e estoura a cota de servicos\ncomo o ntfy.sh — ver decisions.md #47.",
                    "type": "integer"
                },
                "webhooks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/files.WebhookPreset"
                    }
                }
            }
        },
        "files.WebhookPreset": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "events": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "method": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "nyaa.Priorities": {
            "type": "object",
            "properties": {
                "audio": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "codecs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "criteria_order": {
                    "description": "CriteriaOrder é a ordem em que os critérios de sort são aplicados.\nValores válidos: uncensored, source, resolution, codec, fansub, audio, health, size.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "fansubs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ignore_list": {
                    "description": "IgnoreList: substrings (case-insensitive) que descartam o release de vez.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "resolutions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sources": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8091",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Auto Anime Downloader API",
	Description:      "REST API for Auto Anime Downloader daemon",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
